### ISSUE TITLE
Error runanalysis_2ndround_genomic_withgff_gemoma

### ISSUE THREAD

**Issue by up201604214** [molevol-ub/bitacora#1]
I run the runBITACORA_command_line.sh script with files present in the Example_folder, and obtained the following error message ERROR in Scripts/runanalysis_2ndround_genomic_withgff_gemoma: GeMoMa died with error running GeMoMa.

**Comment by Vizueta** [comment]
Dear user,

When using the runBITACORA_command_line.sh script, it also requires to specify the path to GeMoMa binary (-gt option), and the latest version tested is 1.6.4. It seems that some parameters have changed in GeMoMa version 1.7 which I still have to implement in BITACORA, so please try using version 1.6.4 until I update BITACORA scripts to work with v1.7.
Thanks for reporting this issue,

Best,
Joel

**Comment by Vizueta** [comment]
BITACORA have been updated and now works with GeMoMa v1.7.1. Nonetheless, v1.7 contains a bug and it can't be used in our pipeline.
