### ISSUE TITLE
gff file parsing error

### ISSUE THREAD

**Issue by mmarzo** [molevol-ub/bitacora#10]
Hi,
I got this error with a .gff file:
`ERROR in Scripts/Readgff.pm: It does not recognize ID in the GFF3 in: scaffold_4952	AUGUSTUS	transcription_end_site	5737	5737	.	+	.	Parent=g1.t1;`

I have noticed that this "transcription_end_site" annotation does not have an ID as other annotations do, but a Parent tag. I think that is what causes the problem and Bitacora quits.

I don't know how common the transcription_end_site is, so what do you recommend? Shall I remove these lines from my files or maybe Bitacora could ignore them? 

Thanks a lot for your help.

**Comment by mmarzo** [comment]
This is a fragment of our gff file:
`scaffold_4952   AUGUSTUS        gene    1       5737    0.1     +       .       ID=g1;
scaffold_4952   AUGUSTUS        mRNA    1       5737    0.1     +       .       ID=g1.t1;Parent=g1
scaffold_4952   AUGUSTUS        intron  1       134     0.95    +       .       Parent=g1.t1;
scaffold_4952   AUGUSTUS        CDS     135     1904    0.7     +       2       ID=g1.t1.CDS1;Parent=g1.t1
scaffold_4952   AUGUSTUS        exon    135     1904    .       +       .       ID=g1.t1.exon1;Parent=g1.t1;
scaffold_4952   AUGUSTUS        intron  1905    2131    0.72    +       .       Parent=g1.t1;
scaffold_4952   AUGUSTUS        CDS     2132    2509    0.88    +       2       ID=g1.t1.CDS2;Parent=g1.t1
scaffold_4952   AUGUSTUS        exon    2132    2509    .       +       .       ID=g1.t1.exon2;Parent=g1.t1;
scaffold_4952   AUGUSTUS        intron  2510    5399    0.15    +       .       Parent=g1.t1;
scaffold_4952   AUGUSTUS        CDS     5400    5698    0.15    +       2       ID=g1.t1.CDS3;Parent=g1.t1
scaffold_4952   AUGUSTUS        exon    5400    5737    .       +       .       ID=g1.t1.exon3;Parent=g1.t1;
scaffold_4952   AUGUSTUS        stop_codon      5696    5698    .       +       0       Parent=g1.t1;
scaffold_4952   AUGUSTUS        three_prime_utr 5699    5737    0.67    +       .       ID=g1.t1.3UTR1;Parent=g1.t1
scaffold_4952   AUGUSTUS        transcription_end_site  5737    5737    .       +       .       Parent=g1.t1;
scaffold_4952   AUGUSTUS        gene    7733    8310    0.13    -       .       ID=g2;
scaffold_4952   AUGUSTUS        mRNA    7733    8310    0.13    -       .       ID=g2.t1;Parent=g2
scaffold_4952   AUGUSTUS        transcription_end_site  7733    7733    .       -       .       Parent=g2.t1;
scaffold_4952   AUGUSTUS        three_prime_utr 7733    7857    0.38    -       .       ID=g2.t1.3UTR1;Parent=g2.t1
scaffold_4952   AUGUSTUS        exon    7733    8310    .       -       .       ID=g2.t1.exon1;Parent=g2.t1;
scaffold_4952   AUGUSTUS        stop_codon      7858    7860    .       -       0       Parent=g2.t1;
scaffold_4952   AUGUSTUS        CDS     7858    8103    0.61    -       0       ID=g2.t1.CDS1;Parent=g2.t1
scaffold_4952   AUGUSTUS        start_codon     8101    8103    .       -       0       Parent=g2.t1;
scaffold_4952   AUGUSTUS        five_prime_utr  8104    8310    0.32    -       .       ID=g2.t1.5UTR1;Parent=g2.t1
scaffold_4952   AUGUSTUS        transcription_start_site        8310    8310    .       -       .       Parent=g2.t1;
scaffold_1541   AUGUSTUS        gene    9586    21797   0.11    +       .       ID=g3;
scaffold_1541   AUGUSTUS        mRNA    9586    21797   0.11    +       .       ID=g3.t1;Parent=g3
scaffold_1541   AUGUSTUS        transcription_start_site        9586    9586    .       +       .       Parent=g3.t1;`

**Comment by mmarzo** [comment]
Hi again,

I removed the lines with transcription_end_site from the .gff file and then another error popped up:

ERROR in Scripts/Readgff.pm: It does not recognize ID in the GFF3 in: scaffold_4952    AUGUSTUS    transcription_start_site    8310    8310    .    -    .    Parent=g2.t1;
BITACORA died with error

I have removed the lines with transcription_start_site and Bitacora is now running. 

I think maybe the .gff parser of Bitacora needs an update?

**Comment by Vizueta** [comment]
Hi Mar,

Thanks for reporting the issue, I just updated the GFF parser and should work when the "transcription_site" are present in the GFF. 

Best,
Joel

**Comment by mmarzo** [comment]
We have run the last update of the pipeline and all is good. Thanks for sorting this out.
Regards,
Mar
