### ISSUE TITLE
GeMoMa died with error running GeMoMa

### ISSUE THREAD

**Issue by Mahnaz3939** [molevol-ub/bitacora#6]
Hi everyone,
I am using the genome mode script of bitacora. So, I only have "_db.hmm", "_db.fasta", and an assembly fasta file as inputs.
I ran the script with changes in paths and files, but it gives me an error with gemoma. I copied what I got after running it. 
#######################  Running BITACORA  #######################
BITACORA version 1.3
Thu 02 Jun 2022 10:17:52 PM CEST

----------------- Checking input data and prerequisites
Genome fasta parsed correctly
HMMER installed correctly
BLAST installed correctly
GeMoMa-1.8 is installed correctly
Query directory files found and named correctly in my path/DB
Found 1 query databases to search: atps 
Everything looks fine
----------------- DONE

Indexing protein file my path/DB

Building a new DB, current time: 06/02/2022 22:17:58
New DB name:   my path/DB
New DB title:  my path/DB
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Indexing and translating genome file my path/Fb.fa
Found translation for my path/Fb.fa
Found a blast index for my path/Fb.fa

----------------- Starting atps Genomic Gene Identification and Annotation
Doing atps tblastn
Parsing atps tblastn
Using GeMoMa to predict novel genes
FASTA-Reader: Ignoring invalid residues at position(s): On line 9: 46, 49, 51-56, 60-61
ERROR in my path/Scripts/runanalysis_2ndround_v2_genomic_nogff_gemoma: GeMoMa died with error running GeMoMa
BITACORA died with error

Thank you for your help in advance.

**Comment by Vizueta** [comment]
Hello,

GeMoMa v1.8 changed some of the code and that might be the cause of your error. Can you download GeMoMa 1.7.1 [here](https://github.com/molevol-ub/bitacora/blob/master/GeMoMa-1.7.1.zip) and try running bitacora again with your dataset? 

Joel

**Comment by Mahnaz3939** [comment]
Thanks for the response. 
I have to say my error was due to my input file. The sequences for each protein in my fasta_db file were not in one line. I retrieve sequences from ensembl plant database, but each protein must have one line for the header and one line for the sequence.

**Comment by Vizueta** [comment]
Glad that you were able to fix the issue. Note that the fasta can also be interleaved, but always in the correct fasta format.
