### ISSUE TITLE
ERROR in get_gemomav18_gff.pl: It fails finding the gene in GFF CDSID

### ISSUE THREAD

**Issue by guo-cheng** [molevol-ub/bitacora#7]
Hi everyone
I got an error:

----------------- Starting GR Genomic Gene Identification and Annotation
Doing GR tblastn
Parsing GR tblastn
Using GeMoMa to predict novel genes
Doing GR hmmer in newly identified genomic genes
----------------- GR DONE

ERROR in get_gemomav18_gff.pl: It fails finding the gene in GFF CDSID
cp: cannot stat ‘GR/gemoma_outdir/GR_gemoma_genes_novel.pep.fasta’: No such file or directory

Error: Failed to open sequence file GR/GR_genomic_genes_proteins.fasta for reading

readline() on closed filehandle Blastfile at /public1/home/ligch/software/bitacora/Scripts/get_genomic_hmmer_parsed.pl line 19.
readline() on closed filehandle Fasta at /public1/home/ligch/software/bitacora/Scripts/get_fasta_fromalist.pl line 13.
Warning: [blastp] Examining 5 or more matches is recommended
Warning: [blastp] Query is Empty!
Warning: [blastp] Examining 5 or more matches is recommended
Error: mdb_env_open: No such file or directory
BLAST engine error: Empty CBlastQueryVector
readline() on closed filehandle Blastfile at /public1/home/ligch/software/bitacora/Scripts/confirm_GFF_proteins_withlength.pl line 16.
BITACORA died with error

Best wishs!
Guo-cheng

**Comment by Vizueta** [comment]
Dear Guo-cheng,

Regarding the first question in your edited message, the most relevant parameter is the e-value, which you can adjust to retrieve all genes belonging to your gene family of interest. In addition, it is even more important to use protein sequences from closely related species, both as a query and to train the hidden markov model (HMM) used in BITACORA, to increase the likelihood of retrieving divergent members of a gene family. 

As for your error, I need more information to be able to help you. Which version of GeMoMa are you using? And could you send me your full output folder so I can find the specific error. 

Best,
Joel

**Comment by guo-cheng** [comment]
> Dear Guo-cheng,
> 
> Regarding the first question in your edited message, the most relevant parameter is the e-value, which you can adjust to retrieve all genes belonging to your gene family of interest. In addition, it is even more important to use protein sequences from closely related species, both as a query and to train the hidden markov model (HMM) used in BITACORA, to increase the likelihood of retrieving divergent members of a gene family.
> 
> As for your error, I need more information to be able to help you. Which version of GeMoMa are you using? And could you send me your full output folder so I can find the specific error.
> 
> Best, Joel



> 

Hi Joel,

I am working on the gustatory and olfactory receptors annotation in insects, do you have suggestions to annotate these receptors and how to 
I am using PF08395(7tm Chemosensory receptor)  as db.hmm. Do you mean I need to train the new hidden markov model (HMM)?

I am using the GeMoMa-1.9.
The output folder:
![iShot_2023-01-10_09.58.45](https://cdn.liguocheng.top//uPic/iShot_2023-01-10_09.58.45.png)

Best wishs!
Guo-cheng

**Comment by Vizueta** [comment]
Hi Guo-cheng,

You can conduct first a preliminary search using the pfam HMM, but you can conduct afterwards an iterative search in which you include the annotated proteins, training a new HMM profile. I recommend reading the following book chapter to learn and get more familiar: https://doi.org/10.1016/bs.mie.2020.05.015

As for the output folder, I meant the files rather than a screenshot so I can find what is your error. 

Best,
Joel

**Comment by guo-cheng** [comment]
Ok, I get it !

I changed GeMoMa version from 1.9 to 1.7.1, the procedure works well. But i don't know if the version will affect the results a lot.

Best,
Guo-cheng

**Comment by Vizueta** [comment]
Hi Guo-cheng,

Good to hear that it works for you with GeMoMa version 1.7.1. If you are able to compress the BITACORA output folder when using GeMoMa 1.9 and send it to me, I can check and try to debug the error that you got. 

Best,
Joel
