### ISSUE TITLE
GeMoMa died with error running GeMoMa

### ISSUE THREAD

**Issue by rillaxy** [molevol-ub/bitacora#8]
Hi everyone,
I am using the full mode script of bitacora.  "_db.hmm", "_db.fasta", an assembly fasta file ,a protein file and an annotation .gff3 file as inputs. Both Gemoma v1.7.1 and Gemoma v 1.9 were used to run this script, but it gives me an same error with gemoma. I copied what I got after running it. But when I run the example file, everything appears fine.
`#######################  Running BITACORA  #######################
BITACORA version 1.3
2023年 02月 19日 星期日 21:41:59 CST

----------------- Checking input data and prerequisites
GFF parsed correctly
Genome and protein fasta parsed correctly
HMMER installed correctly
BLAST installed correctly
GeMoMa-1.9 is installed correctly
Query directory files found and named correctly in DB
Found 6 query databases to search: 7tm_6 7tm_7 Lig_chan OS-D PBP_GOBP Trehalose_recp 
Everything looks fine
----------------- DONE

Indexing protein file ../Files/SP.pep.fasta
Found a blast index for ../Files/SP.pep.fasta

----------------- Starting 7tm_6 Protein Identification and Annotation
Doing 7tm_6 blastp
Doing 7tm_6 hmmer
Parsing 7tm_6 blastp and hmmer
----------------- 7tm_6 DONE

----------------- Starting 7tm_7 Protein Identification and Annotation
Doing 7tm_7 blastp
Doing 7tm_7 hmmer
Parsing 7tm_7 blastp and hmmer
----------------- 7tm_7 DONE

----------------- Starting Lig_chan Protein Identification and Annotation
Doing Lig_chan blastp
Doing Lig_chan hmmer
Parsing Lig_chan blastp and hmmer
----------------- Lig_chan DONE

----------------- Starting OS-D Protein Identification and Annotation
Doing OS-D blastp
Doing OS-D hmmer
Parsing OS-D blastp and hmmer
----------------- OS-D DONE

----------------- Starting PBP_GOBP Protein Identification and Annotation
Doing PBP_GOBP blastp
Doing PBP_GOBP hmmer
Parsing PBP_GOBP blastp and hmmer
----------------- PBP_GOBP DONE

----------------- Starting Trehalose_recp Protein Identification and Annotation
Doing Trehalose_recp blastp
Doing Trehalose_recp hmmer
Parsing Trehalose_recp blastp and hmmer
----------------- Trehalose_recp DONE

Indexing and translating genome file ../Files/SP.dna.fa
Found translation for ../Files/SP.dna.fa
Found a blast index for ../Files/SP.dna.fa

----------------- Starting 7tm_6 Genomic Gene Identification and Annotation
Doing 7tm_6 tblastn
Parsing 7tm_6 tblastn
Using GeMoMa to predict novel genes
FASTA-Reader: Ignoring invalid residues at position(s): On line 6: 207
FASTA-Reader: Ignoring invalid residues at position(s): On line 112: 650
FASTA-Reader: Ignoring invalid residues at position(s): On line 124: 354, 356-357, 506-508, 511
FASTA-Reader: Ignoring invalid residues at position(s): On line 132: 172, 176
ERROR in /PATH/to/bitacora-BITACORA-v1.4.1/Scripts/runanalysis_2ndround_genomic_withgff_gemoma: GeMoMa died with error running GeMoMa
BITACORA died with error`
Thank you for your help in advance.

**Comment by Vizueta** [comment]
Hello, it seems that there is something wrong with your protein database "7tm_6". Please have a check that the fasta is well formatted and there are not invalid residues. 
In addition, you are using an old version of BITACORA (1.3) that does not support GeMoMa v1.9. Please download the most recent one from github to try again.

**Comment by rillaxy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到您的邮件，祝生活幸福！

**Comment by rillaxy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到您的邮件，祝生活幸福！

**Comment by XuanZhang-Black** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。   您好，我已经收到您的邮件，祝生活幸福！



> 回复
Hi rillaxy,

Have you solved the problem? I met the same error, and I want to know your solution.

Looking for your reply!

Sincerely,
Xuan Zhang

**Comment by rillaxy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到您的邮件，祝生活幸福！
